#!/bin/bash

mvn clean install -Pui-tests-docker-build

mvn verify -Pui-tests-docker-execution \
-DAEM_AUTHOR_URL=${AEM_AUTHOR_URL} \
-DAEM_AUTHOR_USERNAME=${AEM_AUTHOR_USERNAME} \
-DAEM_AUTHOR_PASSWORD=${AEM_AUTHOR_PASSWORD} \
-D_AEM_PUBLISH_URL=${AEM_PUBLISH_URL} \
-DAEM_PUBLISH_USERNAME=${AEM_PUBLISH_USERNAME} \
-DAEM_PUBLISH_PASSWORD=${AEM_PUBLISH_PASSWORD}